/**
 * credits.js — Credits page
 */

export function renderCredits(container) {
    container.innerHTML = `
    <div class="page-header">
      <h1 class="page-title">Credits</h1>
      <p class="page-description">About DCS Sound Mod Creator</p>
    </div>

    <div class="card" style="max-width: 700px; margin-bottom: 24px;">
      <div style="text-align: center; padding: 20px 0;">
        <div style="font-size: 48px; margin-bottom: 12px;">🔊</div>
        <h2 style="font-size: 24px; font-weight: 700; margin-bottom: 4px;">DCS Sound Mod Creator</h2>
        <div style="color: var(--text-muted); font-size: 14px;">Version 1.0.0</div>
        <div class="accent-line" style="max-width: 200px; margin: 16px auto;"></div>
        <p style="color: var(--text-secondary); max-width: 500px; margin: 0 auto;">
          A complete tool for creating DCS World sound mods. Select assets, upload audio, edit SDEF files, and build ready-to-install mod packages.
        </p>
      </div>
    </div>

    <div class="grid-2" style="max-width: 700px;">
      <div class="card">
        <div class="card-title" style="margin-bottom: 12px;">👤 Author</div>
        <div style="font-size: 15px; font-weight: 600; margin-bottom: 4px;">FreeProject089</div>
        <div style="font-size: 13px; color: var(--text-secondary);">Creator & Developer</div>
      </div>

      <div class="card">
        <div class="card-title" style="margin-bottom: 12px;">🎮 Built For</div>
        <div style="font-size: 15px; font-weight: 600; margin-bottom: 4px;">DCS World 2.9.8.1214</div>
        <div style="font-size: 13px; color: var(--text-secondary);">Eagle Dynamics</div>
      </div>
    </div>

    <div class="card" style="max-width: 700px; margin-top: 24px;">
      <div class="card-title" style="margin-bottom: 12px;">🔗 Links</div>
      <div style="display: flex; flex-direction: column; gap: 8px;">
        <a href="https://forums.eagle.ru/" target="_blank" style="color: var(--accent-blue); text-decoration: none; font-size: 14px;">
          🌐 Eagle Dynamics Forums
        </a>
        <a href="https://forums.eagle.ru/showthread.php?t=98014" target="_blank" style="color: var(--accent-blue); text-decoration: none; font-size: 14px;">
          🔊 Sound Modding Thread
        </a>
      </div>
    </div>

    <div class="card" style="max-width: 700px; margin-top: 24px;">
      <div class="card-title" style="margin-bottom: 12px;">📜 Generated Mods Include</div>
      <div style="font-family: var(--font-mono); font-size: 12px; color: var(--accent-green); background: var(--bg-input); padding: 14px; border-radius: var(--radius-md);">
-- Generated with DCS Sound Mod Creator<br/>
-- Credits: [your name here]
      </div>
      <div style="font-size: 12px; color: var(--text-muted); margin-top: 8px;">
        This credit comment is automatically added to every entry.lua generated by this tool.
      </div>
    </div>
  `;
}
